apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace | quote }}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ .Values.repoURL }} 
    chart: cert-manager
    targetRevision: {{ .Values.targetRevision | quote }}
    helm:
      values: |
        ##
        ## Default values for openshift-cert-manager.
        ## This is a YAML-formatted file.
        ## Declare variables to be passed into your templates.
        ##
        global:
          leaderElection:
            # Override the namespace used to store the ConfigMap for leader election
            namespace: {{ .Values.namespace | quote }}
        installCRDs: true

        nodeSelector:
          # run operator on infra nodes, which have the required access to external DNS server (see docs/components/cert-manager)
          node-role.kubernetes.io/infra: ""

        # Make external validation against ext-dns-1 server instead of the default /etc/resolv.conf.
        # And https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check
        extraArgs: ['--dns01-recursive-nameservers-only', '--dns01-recursive-nameservers={{ .Values.acme.dns01.externalServerName }}']

        # Override the namespace used to store DNS provider credentials etc. for ClusterIssuer
        # resources. This namespace will not be automatically created by the Helm chart.
        clusterResourceNamespace: {{ .Values.namespace | quote }}

        ##
        ## End of additional cert-manager resource settings.
        ##
  syncPolicy:
    automated:
      prune: true
      selfHeal: true