apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "Operator to control let's encrypt certificates for OpenShift infra components."
  name: {{ .Values.namespace | quote }}
