# Secret that contains the keys for the external DNS view
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tsigSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{ .Values.tsigSecret.key }}: {{ .Values.global.dns.tsigKeys.external.data | b64enc }}
